name: Deploy Backend to GKE

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        cluster_name: projects/link2day-6cb7c/locations/us-central1/clusters/my-cluster

    # Configure Docker and move to the server directory
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'my-cluster'
        location: 'us-central1'

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/link2day-6cb7c/backend:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
      working-directory: ./server
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/link2day-6cb7c/backend:$GITHUB_SHA"
    
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
      working-directory: ./server

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/link2day-6cb7c/backend:TAG=gcr.io/link2day-6cb7c/backend:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/gke-deployment
        kubectl get services -o wide
      working-directory: ./server