apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deployment
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: "gcr.io/link2day-6cb7c/backend:TAG"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: FIREBASE_PROJECT_ID
              value: "link2day-6cb7c"
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GOOGLE_API_KEY
            - name: ATLAS_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ATLAS_URI