apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: backend
        image: gcr.io/link2day-6cb7c/backend:$GITHUB_SHA
        ports:
        - containerPort: 3000